name: Karate API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Karate Tests
        run: mvn test

      - name: Upload Karate Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: karate-reports
          path: target/karate-reports