name: Karate API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Karate Tests
        run: mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: List directories
        if: always()
        run: |
          echo "Current directory:"
          ls -R
          echo "Target directory:"
          ls -R target || echo "Target directory not found"
          echo "Karate reports directory:"
          ls -R karate-reports || echo "Karate reports directory not found"

      - name: Upload Karate Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: karate-reports
          path: |
            target/karate-reports
            target/surefire-reports
            karate-reports
          if-no-files-found: warn